### ISSUE TITLE
word generator

### ISSUE THREAD

**Issue by Cyrille37** [CEFIM-DL/Pendu2016#2]

**Comment by capetrel** [comment]
bouh

**Comment by capetrel** [comment]
la classe doit mettre le contenu du fichier .txt dans une arraylist
Ensuite il doit compter le nombre de mots présent dans la arraylist intsize().
Générer un Math.random grace au intsize().
Renvoyer l'élément du tableau dont la position est précisée avec random (Object get(index)).

**Comment by Cyrille37** [comment]
OK.
